// Do not edit. This file is machine generated by the Resource DLL Wizard.

library pSample;

{ITE} {DFMFileType} {uSample.dfm}
{ITE} {RCFileType} {pSample_DRC.rc}

{$R 'uSample.dfm' frmSample:TForm}
{$R 'pSample_DRC.res' 'pSample_DRC.rc'}

{$E KOR}

begin
end.